import { Card, SectionHeader } from '@/components/shell/SectionHeader'

const CONTENT: Record<string, { title: string; sections: { h: string; p: string[] }[] }> = {
  terms: {
    title: 'Terms and Conditions',
    sections: [
      { h: 'Practice only', p: ['FakeDuel is a personal practice sportsbook. Balances, deposits, withdrawals and payouts are play money with no cash value and cannot be exchanged for anything.'] },
      { h: 'Data', p: ['Odds and results are sourced from public sports data feeds. Lines marked as practice lines are generated by FakeDuel and do not represent any real sportsbook.'] },
      { h: 'Your data', p: ['Everything you do is stored in this browser only. Use Settings › Export to keep a backup.'] },
    ],
  },
  rg: {
    title: 'Responsible Gaming',
    sections: [
      { h: 'Play for practice, not profit', p: ['FakeDuel exists to practice bankroll management and to learn how odds, parlays and props work before ever risking real money.'] },
      { h: 'Need help?', p: ['If you or someone you know has a gambling problem, call 1-800-GAMBLER (US) or 1-866-531-2600 / ConnexOntario.ca (Ontario). Help is free and confidential.'] },
    ],
  },
  rules: {
    title: 'House Rules',
    sections: [
      { h: 'Settlement', p: ['Bets settle automatically from final box scores. Spreads and totals that land exactly on the number are a push and the wager is refunded.', 'Player props are void if the player does not record any statistics in the game.'] },
      { h: 'Parlays', p: ['A void leg is removed and the parlay is re-priced on the remaining legs. Same Game Parlays use correlated pricing, so their odds are lower than multiplying the legs.'] },
      { h: 'Round robins & teasers', p: ['Round robins are settled as separate parlays for each combination. Teasers with a pushed leg drop to the next smaller teaser; a two-team teaser with a push is refunded.'] },
      { h: 'Cash out', p: ['Cash out is offered on open singles and parlays based on the current live probability of the remaining legs, minus a margin. It is unavailable once a leg has lost.'] },
    ],
  },
  support: {
    title: 'Support',
    sections: [
      { h: 'Something look wrong?', p: ['Odds refresh every minute or so and bets settle within a few minutes of a game going final. If a bet looks stuck, open My Bets and pull to refresh.'] },
      { h: 'Reset', p: ['You can reset the practice account at any time from the Account page. Export a backup first if you want to keep your history.'] },
    ],
  },
  learn: {
    title: 'Learn to Bet',
    sections: [
      { h: 'Moneyline', p: ['Pick the winner outright. Negative odds show how much you need to wager to win $100; positive odds show how much you win on a $100 wager.'] },
      { h: 'Spread', p: ['The favorite gives points and the underdog gets them. Bills -1.5 win the bet if they win by 2 or more.'] },
      { h: 'Totals', p: ['Bet whether the combined score lands over or under the posted number.'] },
      { h: 'Parlays & Same Game Parlays', p: ['Combine multiple selections into one bet. Every leg has to win. SGPs combine selections from a single game with correlated pricing.'] },
      { h: 'Player props', p: ['Bet on an individual performance, like passing yards or an anytime touchdown.'] },
    ],
  },
}

export function StaticPage({ kind }: { kind: keyof typeof CONTENT }) {
  const c = CONTENT[kind]
  return (
    <div className="px-4 lg:px-0">
      <h1 className="text-[20px] font-bold mt-3 mb-3" style={{ color: 'var(--fd-fg)' }}>
        {c.title}
      </h1>
      {c.sections.map((s) => (
        <Card key={s.h}>
          <SectionHeader title={s.h} size="sm" />
          <div className="p-4 space-y-2 text-[14px] leading-5" style={{ color: 'var(--fd-fg-2)' }}>
            {s.p.map((p, i) => (
              <p key={i}>{p}</p>
            ))}
          </div>
        </Card>
      ))}
    </div>
  )
}
